[tool.poetry]
name = "lemonad-bot"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "lemonad_bot"}]

[tool.poetry.dependencies]
python = "^3.9"
pyotp = "^2.8.0"
qrcode = "^7.4.2"
aiogram = {version = "^3.0.0b7", allow-prereleases = true}
peewee = "^3.16.2"
transliterate = "^1.10.2"
aiosqlite = "^0.19.0"


[tool.poetry.group.dev.dependencies]
telethon = "^1.28.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
include = ["lemonad_bot"]
exclude = ["**/secrets"]
ignore = ["lemonad_bot/config.py"]
# defineConstant = { DEBUG = true }
typeCheckingMode = "off"
# reportPropertyTypeMismatch = "off"

reportMissingImports = true
reportMissingTypeStubs = false
